---
- name: Pin docker packages
  ansible.builtin.include_tasks: apt_pinning.yml
  when:
    - docker_apt_pinned_packages is defined

- name: Whitelist Docker archive for unattended upgrades
  ansible.builtin.include_tasks: unattended_upgrades.yml
