---
- name: Check if /etc/postfix/main.cf exists
  ansible.builtin.stat:
    path: /etc/postfix/main.cf
  register: dockertools_postfix_main_cf_status

- name: Adjust mynetwork postfix config for accepting mails from docker networks
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: "mynetworks = 127.0.0.0/8 \\[::ffff:127.0.0.0\\]/104 \\[::1\\]/128"
    line: "mynetworks = 127.0.0.0/8 {{ docker_mynetworks }} [::ffff:127.0.0.0]/104 [::1]/128"
    firstmatch: true
  when: dockertools_postfix_main_cf_status.stat.exists
